"""Module for our creating testing spiders and making html files."""
import scrapy
import json


class JobSpider(scrapy.Spider):
    """Job Spider with website URL."""

    name = "platypus"

    def start_requests(self):
        """Makes the initial request to the page you want to scrape.
        Returns an iterable of Requests, which the Spider can crawl.
        More requests will be generated successively from initial requests."""
        urls = [
            'https://www.indeed.com/jobs?q=developer&l=seattle%2C+wa',
        ]

        for url in urls:
            """For each url you're sending the spider to, make a request.
            Run parse() on the response object you get back."""
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        """Parses the response object and extracts data as dicts.
        Saves the response body in a txt file.
        Name of txt file is generated by the page number in the url."""
        filename = 'indeed_list_view.html'
        with open(filename, 'w') as f:
            f.write(response.body)